export const samsungPhones = [
  {
    model: "Samsung Galaxy S21",
    releaseYear: 2021,
    screenSize: "6.2 inches",
    batteryCapacity: "4000 mAh",
    camera: "Triple 64 MP",
  },
  {
    model: "Samsung Galaxy S21+",
    releaseYear: 2021,
    screenSize: "6.7 inches",
    batteryCapacity: "4800 mAh",
    camera: "Triple 64 MP",
  },
  {
    model: "Samsung Galaxy S21 Ultra",
    releaseYear: 2021,
    screenSize: "6.8 inches",
    batteryCapacity: "5000 mAh",
    camera: "Quad 108 MP",
  },
  {
    model: "Samsung Galaxy Note 20",
    releaseYear: 2020,
    screenSize: "6.7 inches",
    batteryCapacity: "4300 mAh",
    camera: "Triple 64 MP",
  },
  {
    model: "Samsung Galaxy Note 20 Ultra",
    releaseYear: 2020,
    screenSize: "6.9 inches",
    batteryCapacity: "4500 mAh",
    camera: "Triple 108 MP",
  },
  {
    model: "Samsung Galaxy S20",
    releaseYear: 2020,
    screenSize: "6.2 inches",
    batteryCapacity: "4000 mAh",
    camera: "Triple 64 MP",
  },
  {
    model: "Samsung Galaxy S20+",
    releaseYear: 2020,
    screenSize: "6.7 inches",
    batteryCapacity: "4500 mAh",
    camera: "Quad 64 MP",
  },
  {
    model: "Samsung Galaxy S20 Ultra",
    releaseYear: 2020,
    screenSize: "6.9 inches",
    batteryCapacity: "5000 mAh",
    camera: "Quad 108 MP",
  },
  {
    model: "Samsung Galaxy A52",
    releaseYear: 2021,
    screenSize: "6.5 inches",
    batteryCapacity: "4500 mAh",
    camera: "Quad 64 MP",
  },
  {
    model: "Samsung Galaxy A72",
    releaseYear: 2021,
    screenSize: "6.7 inches",
    batteryCapacity: "5000 mAh",
    camera: "Quad 64 MP",
  },
  {
    model: "Samsung Galaxy A32",
    releaseYear: 2021,
    screenSize: "6.4 inches",
    batteryCapacity: "5000 mAh",
    camera: "Quad 64 MP",
  },
  {
    model: "Samsung Galaxy A12",
    releaseYear: 2020,
    screenSize: "6.5 inches",
    batteryCapacity: "5000 mAh",
    camera: "Quad 48 MP",
  },
  {
    model: "Samsung Galaxy A02s",
    releaseYear: 2020,
    screenSize: "6.5 inches",
    batteryCapacity: "5000 mAh",
    camera: "Triple 13 MP",
  },
  {
    model: "Samsung Galaxy Z Fold 2",
    releaseYear: 2020,
    screenSize: "7.6 inches",
    batteryCapacity: "4500 mAh",
    camera: "Triple 12 MP",
  },
  {
    model: "Samsung Galaxy Z Flip",
    releaseYear: 2020,
    screenSize: "6.7 inches",
    batteryCapacity: "3300 mAh",
    camera: "Dual 12 MP",
  },
  {
    model: "Samsung Galaxy M31",
    releaseYear: 2020,
    screenSize: "6.4 inches",
    batteryCapacity: "6000 mAh",
    camera: "Quad 64 MP",
  },
  {
    model: "Samsung Galaxy M51",
    releaseYear: 2020,
    screenSize: "6.7 inches",
    batteryCapacity: "7000 mAh",
    camera: "Quad 64 MP",
  },
  {
    model: "Samsung Galaxy A71",
    releaseYear: 2020,
    screenSize: "6.7 inches",
    batteryCapacity: "4500 mAh",
    camera: "Quad 64 MP",
  },
  {
    model: "Samsung Galaxy A51",
    releaseYear: 2020,
    screenSize: "6.5 inches",
    batteryCapacity: "4000 mAh",
    camera: "Quad 48 MP",
  },
  {
    model: "Samsung Galaxy S10",
    releaseYear: 2019,
    screenSize: "6.1 inches",
    batteryCapacity: "3400 mAh",
    camera: "Triple 12 MP",
  },
  {
    model: "Samsung Galaxy S10+",
    releaseYear: 2019,
    screenSize: "6.4 inches",
    batteryCapacity: "4100 mAh",
    camera: "Triple 12 MP",
  },
  {
    model: "Samsung Galaxy S10e",
    releaseYear: 2019,
    screenSize: "5.8 inches",
    batteryCapacity: "3100 mAh",
    camera: "Dual 12 MP",
  },
  {
    model: "Samsung Galaxy Note 10",
    releaseYear: 2019,
    screenSize: "6.3 inches",
    batteryCapacity: "3500 mAh",
    camera: "Triple 12 MP",
  },
  {
    model: "Samsung Galaxy Note 10+",
    releaseYear: 2019,
    screenSize: "6.8 inches",
    batteryCapacity: "4300 mAh",
    camera: "Quad 12 MP",
  },
  {
    model: "Samsung Galaxy A50",
    releaseYear: 2019,
    screenSize: "6.4 inches",
    batteryCapacity: "4000 mAh",
    camera: "Triple 25 MP",
  },
];
